apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: mdcdll/weather:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: weather
          args: ["foreground"]
