apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather
spec:
  type: NodePort
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: weather
