apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: weather
spec:
  type: NodePort
  ports:
    - name: weather
      port: 443
      targetPort: 80
      protocol: TCP
  selector:
    app: weather
